kind: pipeline
name: julia-latest
clone:
  git:
    image: envelopecity/drone-git-lfs
    
steps:
- name: julia-process
  image: ksteimel/text-analysis:latest
  commands:
    - bash getCorpora.sh
    - julia test/test.jl
  when:
    event:
    - pull_request
    - push
